### ISSUE TITLE
TypeError: Object [ null ] has no method 'createWindow'

### ISSUE THREAD

**Issue by alvassin** [mikeal/spider#24]
When running memory leak test, i get such error:

```
TypeError: Object [ null ] has no method 'createWindow'
    at Spider._handler (/var/www/sitemap/spider/main.js:179:27)
    at Request._callback (/var/www/sitemap/spider/main.js:152:12)
    at Request.self.callback (/var/www/sitemap/node_modules/request/request.js:123:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/var/www/sitemap/node_modules/request/request.js:1047:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/var/www/sitemap/node_modules/request/request.js:998:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by sesam** [comment]
This issue should probably be closed
