### ISSUE TITLE
Cannot read property 'parsingMode' of null

### ISSUE THREAD

**Issue by Quantium** [mikeal/spider#28]
Hello,

Seems like spider is failing. I'm using the NYTimes example. And with node 0.12.0 give me this error:

```
/AmazingDirectory/node_modules/spider/node_modules/jsdom/lib/jsdom.js:41
  if (options.parsingMode === undefined || options.parsingMode === 'auto') {
             ^
TypeError: Cannot read property 'parsingMode' of null
    at Object.exports.jsdom (/AmazingDirectory/node_modules/spider/node_modules/jsdom/lib/jsdom.js:41:14)
    at Spider._handler (/AmazingDirectory/node_modules/spider/main.js:175:26)
    at Request._callback (/AmazingDirectory/node_modules/spider/main.js:148:12)
    at Request.self.callback (/AmazingDirectory/node_modules/spider/node_modules/request/request.js:344:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/AmazingDirectory/node_modules/spider/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/AmazingDirectory/node_modules/spider/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
```

And with node 0.10.36 throw me this:

```
test1

TypeError: Cannot read property 'parsingMode' of null
    at Object.exports.jsdom (/AmazingDirectory/node_modules/spider/node_modules/jsdom/lib/jsdom.js:41:14)
    at Spider._handler (/AmazingDirectory/node_modules/spider/main.js:175:26)
    at Request._callback (/AmazingDirectory/node_modules/spider/main.js:148:12)
    at Request.self.callback (/AmazingDirectory/node_modules/spider/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/AmazingDirectory/node_modules/spider/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/AmazingDirectory/node_modules/spider/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
```

**Comment by WGLayner** [comment]
I got the same error on node 4.2.2

**Comment by Quantium** [comment]
I think te project is no longer maintained...

**Comment by seanowenhayes** [comment]
I think Mikeal still accepts relevant pull requests, at least he did for my last one four years ago. I will see if I can patch it up and send a pull request.

**Comment by lucasfcosta** [comment]
Actually he assigned the ones with open PRs and some contributors as maintainers of this repo, maybe we can get this going again.

**Comment by mikeal** [comment]
yup, if anyone else would like to help maintain i will add you a committer.

**Comment by seanowenhayes** [comment]
@mikeal could you add me please?
